package Carpark;


/**
* Carpark/DateTime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Sunday, 24 March 2019 17:28:02 o'clock GMT
*/

public final class DateTime implements org.omg.CORBA.portable.IDLEntity
{
  public int time = (int)0;
  public int date = (int)0;

  public DateTime ()
  {
  } // ctor

  public DateTime (int _time, int _date)
  {
    time = _time;
    date = _date;
  } // ctor

} // class DateTime
