package Carpark;

/**
* Carpark/EntryGateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 26 March 2019 13:26:25 o'clock GMT
*/

public final class EntryGateHolder implements org.omg.CORBA.portable.Streamable
{
  public Carpark.EntryGate value = null;

  public EntryGateHolder ()
  {
  }

  public EntryGateHolder (Carpark.EntryGate initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Carpark.EntryGateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Carpark.EntryGateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Carpark.EntryGateHelper.type ();
  }

}
