package Carpark;

/**
* Carpark/EventTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 26 March 2019 13:26:25 o'clock GMT
*/

public final class EventTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public Carpark.EventType value = null;

  public EventTypeHolder ()
  {
  }

  public EventTypeHolder (Carpark.EventType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Carpark.EventTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Carpark.EventTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Carpark.EventTypeHelper.type ();
  }

}
