package Carpark;


/**
* Carpark/EventType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 26 March 2019 13:26:25 o'clock GMT
*/

public class EventType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static Carpark.EventType[] __array = new Carpark.EventType [__size];

  public static final int _Entry = 0;
  public static final Carpark.EventType Entry = new Carpark.EventType(_Entry);
  public static final int _Exit = 1;
  public static final Carpark.EventType Exit = new Carpark.EventType(_Exit);

  public int value ()
  {
    return __value;
  }

  public static Carpark.EventType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected EventType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class EventType
