package Carpark;


/**
* Carpark/LocalServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Sunday, 24 March 2019 17:28:02 o'clock GMT
*/

public interface LocalServerOperations 
{
  String location ();
  Carpark.VehicleEvent[] log ();
  void vehicle_in (Carpark.VehicleEvent event);
  void vehicle_out (Carpark.VehicleEvent event);
  boolean vehicle_in_car_park (String registration_number);
  int return_cash_total ();
  void add_entry_gate (String gate_name, String gate_ior);
  void add_exit_gate (String gate_name, String gate_ior);
  void add_pay_station (String station_name, String station_ior);
} // interface LocalServerOperations
