package Carpark;

/**
* Carpark/LocalServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Wednesday, 27 March 2019 15:18:06 o'clock GMT
*/

public final class LocalServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Carpark.LocalServer value = null;

  public LocalServerHolder ()
  {
  }

  public LocalServerHolder (Carpark.LocalServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Carpark.LocalServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Carpark.LocalServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Carpark.LocalServerHelper.type ();
  }

}
