package Carpark;

/**
* Carpark/PayStationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 26 March 2019 13:26:25 o'clock GMT
*/

public final class PayStationHolder implements org.omg.CORBA.portable.Streamable
{
  public Carpark.PayStation value = null;

  public PayStationHolder ()
  {
  }

  public PayStationHolder (Carpark.PayStation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Carpark.PayStationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Carpark.PayStationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Carpark.PayStationHelper.type ();
  }

}
