package Carpark;

/**
* Carpark/TicketHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Wednesday, 27 March 2019 15:18:06 o'clock GMT
*/

public final class TicketHolder implements org.omg.CORBA.portable.Streamable
{
  public Carpark.Ticket value = null;

  public TicketHolder ()
  {
  }

  public TicketHolder (Carpark.Ticket initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Carpark.TicketHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Carpark.TicketHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Carpark.TicketHelper.type ();
  }

}
