package Company;


/**
* Company/CompanyHQOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CompanyHQ.idl
* Tuesday, 26 March 2019 13:26:55 o'clock GMT
*/

public interface CompanyHQOperations 
{
  void raise_alarm (Carpark.VehicleEvent event);
  void register_local_server (String server_name, String server_ior);
} // interface CompanyHQOperations
