package Company;


/**
* Company/CompanyHQ.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CompanyHQ.idl
* Tuesday, 26 March 2019 13:26:55 o'clock GMT
*/

public interface CompanyHQ extends CompanyHQOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompanyHQ
