package Company;

/**
* Company/CompanyHQHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CompanyHQ.idl
* Tuesday, 26 March 2019 13:26:55 o'clock GMT
*/

public final class CompanyHQHolder implements org.omg.CORBA.portable.Streamable
{
  public Company.CompanyHQ value = null;

  public CompanyHQHolder ()
  {
  }

  public CompanyHQHolder (Company.CompanyHQ initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Company.CompanyHQHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Company.CompanyHQHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Company.CompanyHQHelper.type ();
  }

}
